[package]
name = "lem_in"
version = "0.1.0"
edition = "2021"
license = "MIT"

authors = [
  "DoomDuck <docdoomduck@protonmail.com>",
  "Owlly <bourretlucas@gmail.com>",
]

[profile.dev]
opt-level = 2

[profile.release]
debug = true

[dependencies]
rand = "0.8.5"

[dev-dependencies]
