[package]
name = "lem_in"
version = "0.1.0"
edition = "2021"
license = "MIT"

authors = [
  "DoomDuck <docdoomduck@protonmail.com>",
  "Owlly <bourretlucas@gmail.com>",
]

[dependencies]

[dev-dependencies]
rand = "0.8.5"
