on: [push, pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run Tests
    steps:
      - name: "Fetch repository"
        uses: actions/checkout@v3
      - name: "Run tests"
        run: "cargo test"
      - name: "Run doc tests"
        run: "cargo test --doc"

